name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: '3.10'

      - run: pip install poetry
      - run: poetry install -vvv
      - run: poetry run python -m unittest discover -vb tests
      - run: poetry build -vvv --no-interaction
      - run: poetry publish -vvv --no-interaction --password ${{ secrets.PYPI_PASSWORD }}
